Various

diff --git a/jj b/jj
--- a/jj
+++ b/jj
@@ -1,14 +1,18 @@
 #!/bin/bash
 
-# Jump to defined locations via a menu
+# Jump to defined locations via menu
 # dotsource this jj.sh script to load the function into the current shell
 #    . jj.sh
 # If it is not dotsourced, the function will only execute in a subshell
 
+# Check if the script is being sourced
+(return 0 2>/dev/null) || { echo "This script must be run sourced (e.g., '. ./jj')"; exit 1; }
+echo "Will install 'dialog' if required and then enable 'jj'."
+echo "Run 'jj' to view a menu of locations to jump to."
+
 # Check if 2 days have passed since the last update
 if [ $(find /var/cache/apt/pkgcache.bin -mtime +2 -print) ]; then sudo apt update; fi
-
-# Install tools if not already installed
+# Install dialogi if not already installed
 PACKAGES=("dialog")   # "nfs-kernel-server" "nfs-common"
 install-if-missing() { if ! dpkg-query -W "$1" > /dev/null 2>&1; then sudo apt install -y $1; fi; }
 for package in "${PACKAGES[@]}"; do install-if-missing $package; done
